-- MySQL Script generated by MySQL Workbench
-- sex 24 fev 2023 12:37:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CoffeeDelivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CoffeeDelivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CoffeeDelivery` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `CoffeeDelivery` ;

-- -----------------------------------------------------
-- Table `CoffeeDelivery`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoffeeDelivery`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CoffeeDelivery`.`coffee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoffeeDelivery`.`coffee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `subtitle` VARCHAR(45) NULL,
  `subtitle2` VARCHAR(45) NULL,
  `text` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `img_path` VARCHAR(200) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CoffeeDelivery`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoffeeDelivery`.`cart` (
  `user_id` INT NOT NULL,
  `coffee_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`user_id`, `coffee_id`),
  INDEX `fk_user_has_coffee_coffee1_idx` (`coffee_id` ASC) VISIBLE,
  INDEX `fk_user_has_coffee_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_coffee_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `CoffeeDelivery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_coffee_coffee1`
    FOREIGN KEY (`coffee_id`)
    REFERENCES `CoffeeDelivery`.`coffee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CoffeeDelivery`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoffeeDelivery`.`address` (
  `id` INT NOT NULL,
  `road` VARCHAR(150) NOT NULL,
  `ZipCode` INT NOT NULL,
  `number` INT NOT NULL,
  `complement` VARCHAR(100) NOT NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `CoffeeDelivery`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
